version: "3"

services:
    redis:
        image: redis
        ports:
            - 6379:6379
    mysql:
        image: ubuntu/mysql
        command: --default-authentication-plugin=mysql_native_password --collation-server=utf8mb4_unicode_ci
        restart: always
        ports:
            -   3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: flutter_api
